/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc115Sol from "./ERC115.sol";
export type { erc115Sol };
import type * as nftSol from "./Nft.sol";
export type { nftSol };
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
export type { BankAccount } from "./BankAccount";
